version: "2"
services:
  mysql:
      image: kimpa0107/mysql:5.7
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=pado.2015
        - MYSQL_DATABASE=ikimpa.com
      volumes:
        - ./data:/var/lib/mysql
        - ./conf.d:/etc/mysql/conf.d
        - ./mysql.conf.d:/etc/mysql/conf.d/mysql.conf.d
      ports:
        - "3306:3306"
